### ISSUE TITLE
activeIndex resets on intervals

### ISSUE THREAD

**Issue by SleipRecx** [infeng/react-viewer#10]
We have problem with the image viewer activeIndex being reset whenever an interval in our code executes.  Any idea what might cause this? 

Below is a gif illustrating our problem.

![viewer-bug](https://cloud.githubusercontent.com/assets/11886100/23797012/15689466-059e-11e7-8547-1c11c32e0e20.gif)

**Comment by infeng** [comment]
Can you provide offer a re-producible online demo? I will check this better.

**Comment by SleipRecx** [comment]
Demo: [http://markusandresen.no/](http://markusandresen.no/)
Source Code: [https://github.com/SleipRecx/react-imageviewer-demo](https://github.com/SleipRecx/react-imageviewer-demo)

**Comment by infeng** [comment]
Fix in [v2.2.1](https://github.com/infeng/react-viewer/releases/tag/v2.2.1) .
