### ISSUE TITLE
images的src地址不支持服务器端安全认证

### ISSUE THREAD

**Issue by hphpwj** [infeng/react-viewer#100]
images的src地址不支持服务器端安全认证，我的图片地址访问需要在header中添加authentication验证，无法直接实现。然后使用window.URL.createObjectURL(resp. blob()) 赋值给src也无法显示。怎么办？求助

**Comment by infeng** [comment]
可以提供一个 demo 吗

**Comment by hphpwj** [comment]
let downUrl;
const response = await fetch(fileUrl);
response.blob().then((blob) => {
    downUrl = window.URL.createObjectURL(blob);
});

render() {
return (
  <Viewer
    images={[{src: downUrl, alt: ''}]}
  ></Viewer>
  )
}

**Comment by infeng** [comment]
你试下直接用 <img> 标签看下能不能显示 downUrl

**Comment by hphpwj** [comment]
好的，谢谢，我明天试一下，代码在单位电脑上，在chrome开发人员工具中可以看到图片

**Comment by hphpwj** [comment]
<img src={downUrl} alt='' />是能直接显示的，react-viewer好像下面工具栏的缩略图能显示，正常大图不显示

**Comment by infeng** [comment]
可以看下控制台有没有报错，贴一下错误信息

**Comment by hphpwj** [comment]
没报错，我再看一下，可能是我单位电脑上的代码有问题，我明天到单位电脑上试一下。刚才是在个人电脑上随便写了一段代码，点击了一下react-viewer工具栏的中间的那个刷新图标就能正常显示了。

**Comment by infeng** [comment]
感觉是 onload 有问题，我这边无法复现，不好 debug
```
    let img = new Image();
    img.onload = () => {}
```

**Comment by hphpwj** [comment]
> 感觉是 onload 有问题，我这边无法复现，不好 debug
> 
> ```
>     let img = new Image();
>     img.onload = () => {}
> ```

嗯，我现在感觉是我自己写的代码有问题，应该不是react-viewer的问题。谢谢

**Comment by infeng** [comment]
或者你看下能不能给一个最小demo

**Comment by hphpwj** [comment]
在个人电脑上随便写了一段代码，感觉好像找到问题原因了，可能是单位电脑代码中then函数里面的return 了downUrl，但是没返回到最外层。不能正常显示的代码在单位电脑上，现在也忘了怎么写了。谢谢！

**Comment by hphpwj** [comment]
`
let downUrl;
getFile = (src) => {
    fetch(src)
      .then(resp => resp.blob())
      .then(blob => {
        downUrl = window.URL.createObjectURL(blob);
        return downUrl;
      })
      .catch(e => console.error(e));
  }`

`<Viewer images={[{src: downUrl, alt: ''}]} />`这样是可以的
`<Viewer images={[{src: this.getFile(fileSrc), alt: ''}]} />`这样就不行了

**Comment by infeng** [comment]
getFile 是一个异步方法，应该要返回 Promise 并且用 await 吧
```
function getFile(src) {
  return new Promise((resolve) => {
    fetch(src).then(res => res => res.blob())
    .then(blob => window.URL.createObjectURL(blob))
    .then(url => {
      resolve(url);
    })
  })
}

const url = await getFile(src);

<Viewer images={[{ src: url }]}/>
```

**Comment by hphpwj** [comment]
嗯，是的，js异步基础有问题啊，谢谢
