### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by vuthpov** [infeng/react-viewer#104]
Hello,
Can you help me on this? What seem to be the problem?

**Comment by infeng** [comment]
Can you provide a reproduction by codesandbox？

**Comment by vuthpov** [comment]
my bad
i overlooked that your component does not support ssr yet

**Comment by gromov-io** [comment]
> плохо,
> я упустил из виду, что ваш компонент еще не поддерживает ssr


I use NextJS - there are no problems, an example of my code
```
import React, { FC } from 'react'
import dynamic from 'next/dynamic'

const Viewer = dynamic(
  () => import('react-viewer'),
  { ssr: false }
)

export const Gallery: FC = () => {
  return (
    <Viewer
      visible={true}
      onClose={() => {}}
      images={[{src: ''}]}
    />
  )
}

export default Gallery
```

**Comment by bhrugu09** [comment]
> > плохо,
> > я упустил из виду, что ваш компонент еще не поддерживает ssr
> 
> I use NextJS - there are no problems, an example of my code
> 
> ```
> import React, { FC } from 'react'
> import dynamic from 'next/dynamic'
> 
> const Viewer = dynamic(
>   () => import('react-viewer'),
>   { ssr: false }
> )
> 
> export const Gallery: FC = () => {
>   return (
>     <Viewer
>       visible={true}
>       onClose={() => {}}
>       images={[{src: ''}]}
>     />
>   )
> }
> 
> export default Gallery
> ```

worked for me
