### ISSUE TITLE
change images by setstate does not update size info 

### ISSUE THREAD

**Issue by pialin** [infeng/react-viewer#106]
I found that if I change "images" by "setstate" of react, the resolution of  image does not  change accordingly with image(keep old image size), so the new image is distorted. This happened in inline mode. 
This is the [CodeSandbox site](https://codesandbox.io/s/react-viewer-demo-inline-0y563?file=/src/index.js:0-1418). It is modified from your "react-viewer-demo-inline" example. I use the button to change images and the second images is rendered in 1920 * 1080 resolution, however it is a 720 * 1280 picture actually. 
Could you help me?  Thanks very much!

**Comment by infeng** [comment]
Fixed in `v3.2.2` .
