### ISSUE TITLE
I have many warnings about setState on unmount component

### ISSUE THREAD

**Issue by Toxblh** [infeng/react-viewer#11]
<img width="741" alt="screen shot 2017-04-04 at 12 39 36" src="https://cloud.githubusercontent.com/assets/2198153/24650767/edfa6446-1933-11e7-8769-d866dfb879a7.png">
Please repair it

**Comment by Toxblh** [comment]
This problem repeat if i open viewer, edit image(rotate, scale-mouse well, flip) and when i edit i have many warnings

**Comment by Toxblh** [comment]
Very big problem - when i close viewer, send warning dont stop. Plz add on componentUnmount unsubscribe eventListener mouse and another events

**Comment by infeng** [comment]
Can you provide a reproduce demo, let me check better.

**Comment by Toxblh** [comment]
https://monosnap.com/file/nnpjJHPbWKzazrESpXpmQemStU55TW 
What i do:
1. Open viewer with image
2. Some action
3. Close viewer
4. Any mouse scroll create many warning this setState on unmount component
5. Open viewer again
6. Some action create many warning this setState on unmount component
7. Close viewer
8. Very more warnings.
9. If many repeat "open - some actions - close" create very big flow warnings multiplication on count repeat

**Comment by infeng** [comment]
Can you provide a small code demo, I can`t reappear this bug.

**Comment by Toxblh** [comment]
```
showViewer = () => {
    let images =
      this.props[`${this.props.type}Items`]
        .map((item) => ({
          src: this.downloadLink(item.id),
          alt: item.name
        }))

    return (
      <Viewer
        visible
        onClose={() => { this.setState({ mode: GALLERY }) }}
        images={images}
        activeIndex={this.state.attachmentIndex}
      />)
  }
```

**Comment by infeng** [comment]
Fixed in # [v2.2.3](https://github.com/infeng/react-viewer/releases/tag/v2.2.3).

**Comment by Toxblh** [comment]
Hi, @infeng please remove listener onResize after unmount

**Comment by infeng** [comment]
@Toxblh you are right.

**Comment by infeng** [comment]
try [v2.2.4](https://github.com/infeng/react-viewer/releases/tag/v2.2.4) :satisfied:

**Comment by Toxblh** [comment]
All good, nice work) xD
Thank you
