### ISSUE TITLE
viewer能否在某个组件内显示

### ISSUE THREAD

**Issue by hphpwj** [infeng/react-viewer#111]
如题，viewer能否在某个组件内显示，而不是在整个window显示？

**Comment by infeng** [comment]
可以通过 `container ` 属性实现在某个容器内显示，参考 [demo](https://infeng.github.io/react-viewer) 的 inline mode 效果

**Comment by hphpwj** [comment]
好的，谢谢，学习学习

**Comment by hphpwj** [comment]
太棒了，谢谢！
