### ISSUE TITLE
CustomToolbar example

### ISSUE THREAD

**Issue by justice-art** [infeng/react-viewer#117]
Hello :-) Can someone provide an example for custom toolbar, please ?

**Comment by infeng** [comment]
@justice-art  You can see this [demo](https://codesandbox.io/s/react-viewer-demo-0w1r2?file=/src/index.js)

**Comment by justice-art** [comment]
> @justice-art You can see this [demo](https://codesandbox.io/s/react-viewer-demo-0w1r2?file=/src/index.js)

Thanks !
