### ISSUE TITLE
Cannot display array of image

### ISSUE THREAD

**Issue by virketchup** [infeng/react-viewer#129]
```
<Viewer
       visible={visible}
       onClose={() => { setVisible(false); }}
       images={[{src:image}]}
/>
```

The image is an array of strings. If the array contains more than 1 string it won't display.

**Comment by TaylanDurmaz** [comment]
try this

```
<Viewer
       visible={visible}
       onClose={() => { setVisible(false); }}
       images={image.map(img => ({src: img})}
/>

```

**Comment by virketchup** [comment]
> try this
> 
> ```
> <Viewer
>        visible={visible}
>        onClose={() => { setVisible(false); }}
>        images={image.map(img => ({src: img})}
> />
> ```

Thank you so much! Did not think of using the map function
