### ISSUE TITLE
react V0.14.4版本中好像不支持transitionend 事件，图片出不来

### ISSUE THREAD

**Issue by ChasHong** [infeng/react-viewer#14]
在react V0.14.7版本中好像不支持transitionend 事件。
所以预览的时候图片一直出不来，为了兼容低版本

      if (this.state.visible && this.state.transitionEnd) { 
        // 触发不了transitionend事件 这里一直进不来
        let images = this.props.images || [];
        if (images.length > 0 && this.state.activeIndex >= 0) {
          activeImg = images[this.state.activeIndex];
        }
      }

**Comment by infeng** [comment]
我看一下，可以考虑在低版本取消动画

**Comment by infeng** [comment]
Fix in [v2.2.5](https://github.com/infeng/react-viewer/releases/tag/v2.2.5).
