### ISSUE TITLE
Option to add close on overlay click?

### ISSUE THREAD

**Issue by Teal-labs-developer** [infeng/react-viewer#16]
can we have a prop to close the viewer on overlay click?

**Comment by infeng** [comment]
Sorry, I don`t know what 'overlay click' mean.

**Comment by Teal-labs-developer** [comment]
black overlay over screen with class "react-viewer-mask", we can have onclick handler with prop 
bool check

**Comment by infeng** [comment]
I provide a prop to determine whether close after click `mask`, like this:
```javascript
<Viewer
  closeWithClickMask
/>
```

**Comment by infeng** [comment]
see [v2.2.6](https://github.com/infeng/react-viewer/releases/tag/v2.2.6).
