### ISSUE TITLE
Working with any kind of file?

### ISSUE THREAD

**Issue by seemple** [infeng/react-viewer#19]
Hi!

The readme talks about an "images" array. Could we put the viewerjs accepted files instead? (pdf and openDocument format )

Thanks,

**Comment by infeng** [comment]
Let me try.

**Comment by seemple** [comment]
Thanks!

**Comment by infeng** [comment]
Maybe direct use `<object>` will be better :laughing: .

**Comment by seemple** [comment]
Ok, will do. Thanks!
