### ISSUE TITLE
Viewer can't be fixed.

### ISSUE THREAD

**Issue by SiminWong** [infeng/react-viewer#21]
Viewer can't be fixed in viewport on a long page.

**Comment by infeng** [comment]
When `Viewer` show, scrollbar should be hidden.

**Comment by infeng** [comment]
Fixed in [2.3.2](https://github.com/infeng/react-viewer/releases/tag/v2.3.2) .

**Comment by SiminWong** [comment]
Viewer positioning error.  When view show after page scroll, it should be fixed in viewport rather than page top.

**Comment by SiminWong** [comment]
For a prefect experience, viewer should be closed entirely before scrollbar show.  It just a suggestion.

**Comment by infeng** [comment]
Try 2.3.3 .

**Comment by SiminWong** [comment]
Maybe you change something cause image be scrolled to left and  zoomed in by mouse scrolling now. you can test it in demo.

**Comment by infeng** [comment]
Can you provide a gif?

**Comment by SiminWong** [comment]
`<div>
          <button onClick={() => { this.setState({ visible: !this.state.visible }); } }>show</button>
          <Viewer
              visible={this.state.visible}
              onClose={() => { this.setState({ visible: false }); } }
              images={[{src: 'https://raw.githubusercontent.com/infeng/react-viewer/master/demo/images/image4.jpg', alt: '测试'}]}
          />
        </div>`

![gif](https://user-images.githubusercontent.com/26730827/36723943-9e62e9d2-1bec-11e8-80f9-647aa3fb4157.gif)

**Comment by infeng** [comment]
@SiminWong I want to know your browser version.

**Comment by SiminWong** [comment]
chrome 64.0.3282.140

**Comment by infeng** [comment]
Sorry, I can`t reappear.

**Comment by SiminWong** [comment]
Oh, I find it. When you working with two monitors, It work well at major one but not at the second.

**Comment by infeng** [comment]
Get it, I will fix.

**Comment by SiminWong** [comment]
thank you so much.

**Comment by infeng** [comment]
Try 2.3.4.

**Comment by SiminWong** [comment]
Perfect, thanks!
