### ISSUE TITLE
Scroll affect viewer if I set a container for Viewer

### ISSUE THREAD

**Issue by Toxblh** [infeng/react-viewer#22]
So, I think it's not a bug, maybe to need do it optional.
When I use `container` attribute like in your example in demo site when active inline mode. When you scroll the page in inline mode (you can resize the window to active a scroll) viewer have a reaction on scroll page, and you mouse outside container with Viewer

I use the last version the package

**Comment by infeng** [comment]
Fixed in #23.

**Comment by gajju3588** [comment]
I am still seeing this issue with '2.5.0'

**Comment by infeng** [comment]
@gajju3588 Can you offer a reproduction? you can use [CodeSandbox](https://codesandbox.io/s/lykw37v3zq).
