### ISSUE TITLE
downloading images

### ISSUE THREAD

**Issue by SkyLin0909** [infeng/react-viewer#24]
If i want to implement an API for downloading images。
Is it troublesome to configure?

**Comment by infeng** [comment]
你是想在工具栏增加一个下载按钮吗

**Comment by SkyLin0909** [comment]
对的，想在底部icon加入一个下载的图片，传入当前展示图片的src即可

**Comment by infeng** [comment]
我加一个配置工具栏的属性吧

**Comment by SkyLin0909** [comment]
嗯，想自己fork一份改的，奈何对typescript只是入门

**Comment by infeng** [comment]
不好意思，最近比较忙，一直拖着没做，因为下载图片需要服务端支持，所以增加一个`downloadUrl`属性来配置下载地址

**Comment by SkyLin0909** [comment]
谢谢老哥！

**Comment by infeng** [comment]
Close in [v2.3.6](https://github.com/infeng/react-viewer/releases/tag/v2.3.6).
