### ISSUE TITLE
Download and changeable

### ISSUE THREAD

**Issue by GrishmaM** [infeng/react-viewer#25]
Can u make changeable to read from props ?
Download it directly without opening the new window 
README change download to downloadable in props list

**Comment by infeng** [comment]
Sorry, I do not know what you mean accurately.

**Comment by GrishmaM** [comment]
you made changeable prop default to true in your code, can accept it from props?

**Comment by infeng** [comment]
See [v2.3.9](https://github.com/infeng/react-viewer/releases/tag/v2.3.9).

**Comment by GrishmaM** [comment]
you made changeable to read from props, which also removed reset button
