### ISSUE TITLE
Custom toolbar

### ISSUE THREAD

**Issue by yinxin630** [infeng/react-viewer#27]
I need to add a custom button to the toolbar. But props doesn't seem to provide this feature. Can the current version fulfill my needs? If not, is there any plan to add this feature?

**Comment by infeng** [comment]
Can not curtom toolbar in current version, Do you want to add custom button in the end of the toolbar?

**Comment by yinxin630** [comment]
Yes. And I also need to hide some of the buttons. At the moment I am hidden via css

**Comment by infeng** [comment]
@yinxin630

**Comment by infeng** [comment]
@yinxin630 The custom toolbar config like this, what parameter do you want to pass in `onClick` function
``` typescript
interface ToolbarConfig {
  key: string;
  actionType?: number;
  render?: React.ReactNode;
  onClick?: () => void;
}
```

**Comment by yinxin630** [comment]
As long as I can know which toolbar button was clicked on

**Comment by yinxin630** [comment]
I still have an idea. For the close operation, except click on the button in the upper right corner and the ESC button on the keyboard. Can I add a mode that clicks the mask to close. And allow me to choose which modes to use on my own.

**Comment by infeng** [comment]
Current version, You can use `onMaskClick`.

**Comment by yinxin630** [comment]
Ok, thanks~
