### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by Daguod** [infeng/react-viewer#28]
你好 ,  我在练习reactDemo的时候 在移动端有一个查看图片的需求 故此从网上找到了这个插件 
  在实际操作过程中 发现该插件对移动端好像并不友好
   目前已知两个问题:
        1.  没有可以修改Parent/child元素style的api;
        2.  没有提供手势缩放的效果, 按钮缩放略显鸡肋;
     希望可以获得改善 提高使用体验 谢谢.

**Comment by infeng** [comment]
会考虑出一个mobile版本
