### ISSUE TITLE
Zoom speed

### ISSUE THREAD

**Issue by arthursoas** [infeng/react-viewer#30]
Hi,
Is there some way to set the speed of the zoom?
I need the zoom to be two times faster than currently.

Thanks!

**Comment by infeng** [comment]
Can not set zoom speed now, I will add a new props `zoomSpeed`.

**Comment by infeng** [comment]
[v2.5.0](https://github.com/infeng/react-viewer/releases/tag/v2.5.0) add `zoomSpeed`.
