### ISSUE TITLE
no support for mobile phones

### ISSUE THREAD

**Issue by jligeza** [infeng/react-viewer#31]
On my mobile phone, dragging and zooming (by pinching) doesn't work, and that's a big shame. Especially dragging, which makes this component pretty much unusable for mobiles.

**Comment by infeng** [comment]
`react-viewer` does not support mobile.

**Comment by infeng** [comment]
You can try [react-viewer-mobile](https://github.com/infeng/react-viewer-mobile), but there's some problems with scaling.
