### ISSUE TITLE
how to set the default size of image?

### ISSUE THREAD

**Issue by pycodev** [infeng/react-viewer#38]
there is any option which can control it?

3q :)

**Comment by infeng** [comment]
Now it's not supported, I would consider supporting.

**Comment by pycodev** [comment]
@infeng  I also find the download icon not work for me, maybe it's a bug.

thx for your response.

**Comment by infeng** [comment]
Can you offer a reproduction in [CodeSandbox](https://codesandbox.io/s/71kwl255l1) ?

**Comment by pycodev** [comment]
sorry, The code is only available inside company.

I can describe the way I use this component: 

with webpack , I import the image file and then pass the value to <Viewer/> as the `src` prop。

**Comment by infeng** [comment]
Have you set `downloadUrl`? you can see [ImageDecorator](https://github.com/infeng/react-viewer#imagedecorator).

**Comment by infeng** [comment]
[v2.6.0](https://github.com/infeng/react-viewer/releases/tag/v2.6.0) support `defaultSize`.
