### ISSUE TITLE
Error: No PostCSS Config found

### ISSUE THREAD

**Issue by Muran-Hu** [infeng/react-viewer#40]
import 'react-viewer/dist/index.css';

这句代码会导致下面这个错误：

ERROR in ./node_modules/react-viewer/dist/index.css (./node_modules/css-loader!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js!./node_modules/react-viewer/dist/index.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: No PostCSS Config found in: /Users/hmr/Documents/ngx-trunk/node_modules/react-viewer/dist
    at config.load.then (/Users/hmr/Documents/ngx-trunk/node_modules/postcss-load-config/src/index.js:55:15)
    at <anonymous>
 @ ./node_modules/react-viewer/dist/index.css 2:14-130 21:1-42:3 22:19-135
 @ ./src/common/components/media/MediaViewer.js
 @ ./src/web/entity/EntityViewer.js
 @ ./src/web/entity/EntityBody.js
 @ ./src/web/entity/Entity.js
 @ ./src/web/app/routes.js
 @ ./src/web/app/App.js
 @ ./src/web/app/Root.js
 @ ./src/web/main.js
 @ ./src/web/index.js
 @ multi webpack-hot-middleware/client?path=http://192.168.1.101:8080/__webpack_hmr ./src/web/index.js

请大神指教！谢谢

**Comment by infeng** [comment]
可以给一个重现的项目吗

**Comment by Muran-Hu** [comment]
下面是我的code：
// @flow
import React from 'react'
import Viewer from 'react-viewer'
import 'react-viewer/dist/index.css'
import { MediaViewerProps } from './types'

const MediaViewer = ({
  click,
  fileName,
  isOpen,
  onLoad,
  url,
  previewStatus = 2,
}): MediaViewerProps => {
  if (previewStatus === 2) {
    return (
      <div>
        <img
          alt={fileName}
          onClick={click}
          onLoad={onLoad}
          src={url}
        />
        <Viewer
          images={[{ alt: fileName, src: url }]}
          onClose={click}
          visible={isOpen}
        />
      </div>
    )
  }
  return (
    <div>
      The creation of the preview file has not completed
      or the file type is not currently supported.
    </div>
  )
}

export default MediaViewer

**Comment by Muran-Hu** [comment]
> 可以给一个重现的项目吗

下面是我的code：
```
// @flow
import React from 'react'
import Viewer from 'react-viewer'
import 'react-viewer/dist/index.css'
import { MediaViewerProps } from './types'

const MediaViewer = ({
  click,
  fileName,
  isOpen,
  onLoad,
  url,
  previewStatus = 2,
}): MediaViewerProps => {
  if (previewStatus === 2) {
    return (
      <div>
        <img
          alt={fileName}
          onClick={click}
          onLoad={onLoad}
          src={url}
        />
        <Viewer
          images={[{ alt: fileName, src: url }]}
          onClose={click}
          visible={isOpen}
        />
      </div>
    )
  }
  return (
    <div>
      The creation of the preview file has not completed
      or the file type is not currently supported.
    </div>
  )
}

export default MediaViewer
```

**Comment by Muran-Hu** [comment]
import 'react-viewer/dist/index.css'

我现在测试是这句代码引起的错误，但是没有找到解决办法。

**Comment by infeng** [comment]
可以贴一下你的webpack配置吗
