### ISSUE TITLE
Renders in full screen instead of inline

### ISSUE THREAD

**Issue by dortonway** [infeng/react-viewer#42]
react-viewer@2.6.0

I have the following code:

```
                    <Grid container alignItems="center" justify="center">
                      <Grid item xs={12}>
                        <Typography>
                          Документ "{document.name}" (id {document.id})
                        </Typography>
                      </Grid>
                      <Grid item xs={8} className={classes.images}>
                        <div
                          ref={ref => (this.container = ref)}
                          className={classes.viewer}
                        />
                      </Grid>
                      <Grid item xs={4}>
                        right
                      </Grid>

                      <Viewer
                        visible
                        container={this.container}
                        zoomSpeed={0.6}
                        images={document.images.map((image, i) => ({
                          src: `data:image/${
                            document.imageExtensions[i]
                          };base64,${image}`,
                          alt: `Страница ${i + 1} `,
                        }))}
                      />
                    </Grid>
```

If I leave it as is it renders in full screen mode. But if I rerender it with any changes to state:

```
  componentDidMount() {
    this.fixViewerInterval = setInterval(() => {
      this.setState({ fixViewer: true });
    }, 500);
  }

  componentWillUnmount() {
    clearInterval(this.fixViewerInterval);
  }
```

viewer appears in the place it has to be (but full screen blinks one time at page loading and body has "overflow: hidden").

So how to render it correctly without interval fix?

I'm not sure is it a bug or incorrect usage.

**Comment by joepaynes** [comment]
Any luck with this issue? I am experiencing the same, and have used a lifecycle method to cause a quick change to state

`class ImageViewer extends Component {
    // DISPLAY IMAGES INSIDE VIEWER
    // https://github.com/infeng/react-viewer

    constructor(props) {
        super(props);

        this.state = {
            loading: false,
        }

        this.imageView = React.createRef();
    }

    componentDidMount() {
        this.setState({loading: true});
    }
    
    render() {
        const { classes, data } = this.props;
        const node = this.imageView.current 

        return (
            <div>
                <Viewer
                    visible
                    onClose={() => { alert("k") } }
                    images={[{src: `${data}`}]}
                    container={node}
                    attribute={false}
                    noImgDetails
                    noClose
                    noNavbar
                    changeable={false}
                    zoomSpeed={0.2}
                />
                <div ref={this.imageView} className={classes.image}></div>
            </div>
        )
    }
}

export default withStyles(styles)(ImageViewer);`
