### ISSUE TITLE
how to Disable keyboard support ? 

### ISSUE THREAD

**Issue by bdevika** [infeng/react-viewer#44]

**Comment by infeng** [comment]
I don't have time recently, welcome pr.

**Comment by infeng** [comment]
[v2.7.0](https://github.com/infeng/react-viewer/releases/tag/v2.7.0) support disable keyboard support.

**Comment by bdevika** [comment]
Thank you ..., It helped a lot. :)

**Comment by bdevika** [comment]
One more Query how to get the current image index?

**Comment by bdevika** [comment]
Ok.. Thanks in advance:)

**Comment by infeng** [comment]
[v2.8.0](https://github.com/infeng/react-viewer/releases/tag/v2.8.0) add `onChange` to get current index

**Comment by bdevika** [comment]
hi, 

One Query how to make image full-screen on over ?
