### ISSUE TITLE
我想一开始就是100%显示图片

### ISSUE THREAD

**Issue by 550406066** [infeng/react-viewer#46]
RT

**Comment by infeng** [comment]
我加个属性控制默认缩放比例吧

**Comment by infeng** [comment]
现在首次打开对宽度高度是有限制的，不能超过屏幕最大宽度和高度

**Comment by 550406066** [comment]
对，确实需要一个比例，因为我的应用场景就是查看100%的大图，所以很需要这个功能

**Comment by infeng** [comment]
我加两个属性吧，一个解除限制，一个设置默认缩放比例

**Comment by 550406066** [comment]
好，大佬，等你更新的消息

**Comment by infeng** [comment]
[v2.8.0](https://github.com/infeng/react-viewer/releases/tag/v2.8.0) 加了 `noLimitInitializationSize` 和 `defaultScale`，解除最大尺寸限制和设置默认缩放比例。
