### ISSUE TITLE
how to remove  border 

### ISSUE THREAD

**Issue by sundariya** [infeng/react-viewer#49]
i want to  remove or change  border  how  to  do this .

**Comment by sundariya** [comment]
please  replty  as soon as as possible

**Comment by infeng** [comment]
Where border mean, you can provide a screenshot

获取 Outlook for iOS<https://aka.ms/o0ukef>

________________________________
发件人: suraj kumar sundariya <notifications@github.com>
发送时间: 星期三, 二月 6, 2019 14:19
收件人: infeng/react-viewer
抄送: Subscribed
主题: Re: [infeng/react-viewer] how to remove border (#49)


please replty as soon as as possible

―
