### ISSUE TITLE
After the contextmenu is triggered, the drag state is continuously maintained.

### ISSUE THREAD

**Issue by zf1517** [infeng/react-viewer#51]
After the right mouse button triggers the contextmenu, the mouseup event is invalid, causing the drag state to remain. It is recommended to close the right mouse drag.
`
handleMouseDown = (e) => {
    if (!this.props.visible || !this.props.drag) {
      return;
    }
    e.preventDefault();
    e.stopPropagation();
    if(e.button === 0){
        this.setState({
            isMouseDown: true,
            mouseX: e.nativeEvent.clientX,
            mouseY: e.nativeEvent.clientY,
        });
    }
  }
`

**Comment by infeng** [comment]
Welcome pr.

**Comment by infeng** [comment]
Fixed in `v2.10.2`
