### ISSUE TITLE
Not able to see the images when "Viewer" is placed inside a modal

### ISSUE THREAD

**Issue by adred8** [infeng/react-viewer#52]
I placed the Viewer with inline container in a modal. Only seeing the small image previews and close button. When trying the Viewer in modal view, the images are getting displayed behind main modal. What can I do to fix this? I want to use inline view

Thanks

**Comment by infeng** [comment]
Can you provide a reproduction by [codesandbox](https://codesandbox.io/s/9zpxkxrvy).

**Comment by adred8** [comment]
It seems to be working in code sandbox https://codesandbox.io/s/7y44k6llo1

Will check my actual code again

**Comment by adred8** [comment]
I did not give defined height and width to the "container" given to the viewer. So the canvas was taking no form
