### ISSUE TITLE
Need to specify fixed height for container in inline mode

### ISSUE THREAD

**Issue by adred8** [infeng/react-viewer#54]
#52 

When container is not given height, the viewer doesn't show up properly.

https://codesandbox.io/s/7y44k6llo1

Mention in the documentation that height is mandatory for the container. Also need to be checked if inline mode can be made to work when no specific height is given

**Comment by infeng** [comment]
Maybe I can give the viewer a minimum height.

**Comment by infeng** [comment]
Fiexed in `v2.8.1` .
