### ISSUE TITLE
Image Display

### ISSUE THREAD

**Issue by howardhsien** [infeng/react-viewer#6]
First, React-Viewer is pretty good! The function is strong, i really like it. Thank you for building it.

However, when I want to display a high resolution size picture. The way it displays bothers me. I wish it could be like 
<img width="1278" alt="2016-12-19 7 50 49" src="https://cloud.githubusercontent.com/assets/9826674/21311891/7eee3576-c624-11e6-9298-8c57e3203f10.png">
which is well placed and well zoomed in the center
but the look will be like
<img width="1280" alt="2016-12-19 7 45 13" src="https://cloud.githubusercontent.com/assets/9826674/21311868/64db6758-c624-11e6-94b3-f4683c4beef5.png">
which is extended to full height

Do you have any idea how to fix this problem?

**Comment by infeng** [comment]
i will fix it soon, thanks your issue

**Comment by infeng** [comment]
@howardhsien  I try a high resolution picture and display well, i need more information like your react-viewer`s version and what browser do you use. 
![react-viewer-pic 1](https://cloud.githubusercontent.com/assets/16483610/21315939/6138e890-c639-11e6-832b-a5943d9433b1.png)

**Comment by infeng** [comment]
close via commit [d1abef3](https://github.com/infeng/react-viewer/commit/d1abef32bc33cd8097586a3c49737ea59ba78dbe)

**Comment by howardhsien** [comment]
Thanks for the reply, my react-viewer is v1.2.3.
And I am using chrome with version 54.0.2840.98.

**Comment by infeng** [comment]
@howardhsien you can try 1.2.4

**Comment by howardhsien** [comment]
I have updated to v1.2.4, however the display is the same. 
<img width="1280" alt="2016-12-20 1 12 29" src="https://cloud.githubusercontent.com/assets/9826674/21338985/05476a84-c6b6-11e6-859d-be2267fd0556.png">

Here is the link of my problem pic
http://tshop.r10s.com/f73/d35/4fe3/a6be/b027/62f8/64c3/1188e5aa4f005056ae7405.jpg
I found out that, it may be the cause that the image i put in viewer is more square-like. Is there any way to fix the look of this kind of pic?
Thanks!!

**Comment by infeng** [comment]
@howardhsien I add your image into the demo page, it display well, you can see [demo](https://infeng.github.io/react-viewer/).

**Comment by howardhsien** [comment]
Thank You!!!  
I rerun my server and it succeeded as well, thank you for your help!
