### ISSUE TITLE
MouseWheel Zoom out not working in IE 11

### ISSUE THREAD

**Issue by nilasuba** [infeng/react-viewer#67]
When using the Mouse wheel on images, the images zooms in on both direction of mousewheel and doesn't zoom out.

e.deltaY is undefined in IE 11 for some reason, I changed it to e.wheelData and it works.

**Comment by saimib** [comment]
Yes I was about to raise this as well, I can create a Pull request for this issue

**Comment by infeng** [comment]
@saimib Welcome pr.

**Comment by infeng** [comment]
Fixed in `v2.10.0`
