### ISSUE TITLE
如何取消鼠标滚动缩放功能？

### ISSUE THREAD

**Issue by itHulk** [infeng/react-viewer#69]
如题

**Comment by infeng** [comment]
暂时不支持，有需要的话可以加

**Comment by itHulk** [comment]
> 暂时不支持，有需要的话可以加

好的，谢谢大佬。  还有就是viewer的自动全屏播放功能。  我看目前也不支持是吧，没看到自动播放按钮

**Comment by infeng** [comment]
这个库一开始的需求是让使用者可以操作图片，而不是单纯的轮播，所以就没考虑加自动播放

**Comment by infeng** [comment]
`v2.10.0` 支持 `disableMouseZoom`
