### ISSUE TITLE
API Suggestion

### ISSUE THREAD

**Issue by howardhsien** [infeng/react-viewer#7]
Hi @infeng : 

I have some suggestions for React-Viewer.
1. I would like the image to be fixed in the center. Or it should be a property to be set in the <Viewer> Ex: 
`<Viewer imgFixed = {true} />`

2. Some of the functions in the function bar should be optional. Like 
<img width="1279" alt="2016-12-27 5 40 47" src="https://cloud.githubusercontent.com/assets/9826674/21496829/55cb88f4-cc5c-11e6-8055-93e007605bd7.png">
Ex: 

```
const viewerFunctionBarSetting = {
  flip-horizontal: true,
  flip-vertical: false,
  rotate-clockwise: true,
  rotate-counterclockwise: false,
  zoom: true, //(availability for zooming in and out)
}
function render = ()=>(
   <Viewer 
       functionBarSetting = {this.viewerFunctionBarSetting}
       resolution-visibility = {false}/>
)

```
These are my suggestions for the react-viewer!

**Comment by infeng** [comment]
@howardhsien  thanks for you suggestion, i will add this features soon.
i can`t understand the first suggestion well, it means the image can not move?

**Comment by howardhsien** [comment]
@infeng Yes, I mean the image should be fixed in the center. In the version now, the image can be dragged.

Thanks! I really like your react-viewer, I hope it will get even better!

**Comment by infeng** [comment]
@howardhsien i think the functions should set visible according to the function, it seems better.
```javascript
<Viewer
visible={this.state.visible}
onClose={() => { this.setState({ visible: false }); } }
images={images}
zoomable={true}
rotatable={false}
scalable={true}
/>
```

**Comment by howardhsien** [comment]
@infeng do you mean zoomable, rotatable, scalable which means the visibility and functionality of functions on function bar to be parameter in <Viewer>?
If so, I think it is good!

**Comment by infeng** [comment]
v2.2.0 has released.
