### ISSUE TITLE
activeIndex 不受控

### ISSUE THREAD

**Issue by jiechud** [infeng/react-viewer#71]
通过Props去更改 activeIndex不受控，如果我更改 images 数据, 相应的 activeIndex 也会更新。

**Comment by infeng** [comment]
感觉反馈，我看下

**Comment by jiechud** [comment]
提 pull request 会快速给合并吗? bug 挺着急的，要不只能自己发 npm 包了

**Comment by jiechud** [comment]
@infeng  建议增加两个属性， defaultActiveIndex 是组件初始化用的index，  activeIndex 作为受控属性

**Comment by infeng** [comment]
可以马上发，你提pr

获取 Outlook for iOS<https://aka.ms/o0ukef>
________________________________
发件人: qiaojie <notifications@github.com>
发送时间: Friday, August 16, 2019 12:39:48 PM
收件人: infeng/react-viewer <react-viewer@noreply.github.com>
抄送: feng zhi hao <fzhihao@outlook.com>; Mention <mention@noreply.github.com>
主题: Re: [infeng/react-viewer] activeIndex 不受控 (#71)


@infeng<https://github.com/infeng> 建议增加两个属性， defaultActiveIndex 是组件初始化用的index， activeIndex 作为受控属性

―

**Comment by jiechud** [comment]
@infeng #72  已提 PR，看有问题没，没有请 merge

**Comment by jiechud** [comment]
请看下这个 Demo， https://codesandbox.io/s/laughing-smoke-sxynp  按以下步骤 
1. 点击按钮，打开图片浏览器
2. 切换下一张图片
3. 点击更改 index，这时候我把 image 替换成了 4张， 更改 activeIndex 为 2
4. 结果，通过onChange 改变，activeIndex 变成了 0

**Comment by infeng** [comment]
看到了，我改一下

**Comment by jiechud** [comment]
@infeng  更新了吗？

**Comment by infeng** [comment]
准备了，我测试通过就发布

**Comment by infeng** [comment]
Fixed in `v2.10.2`

**Comment by jiechud** [comment]
![image](https://user-images.githubusercontent.com/9709396/63155579-6e75c880-c045-11e9-89be-e32cfde40a92.png)

我看你改了那么多，适配一下 `handleChangeImg` 方法是不是就好了，其它不用改

**Comment by infeng** [comment]
`componentWillReceiveProps ` 在 React v16.9.0 会出现警告，所以顺便改一下

**Comment by jiechud** [comment]
componentDidUpdate 生命周期里做，会造成多一次渲染吧，渲染完后， 通过改 activeIndex ，还会造成一次渲染吧。 3.0 重构的时候考虑下 `getDerivedStateFromProps` ?

**Comment by infeng** [comment]
3.0 会改为用 Hooks
