### ISSUE TITLE
image isn't shown on the right place

### ISSUE THREAD

**Issue by howardhsien** [infeng/react-viewer#8]
Hi @infeng :
I have upgraded my react-viewer to 2.2.0. However there seems some problems.
<img width="1280" alt="2017-01-04 8 20 29" src="https://cloud.githubusercontent.com/assets/9826674/21642130/4f2bfca8-d2bb-11e6-8d00-c030180fe342.png">

As you can see in the pic. The image which should be in the center now is in the bottom of the page.

**Comment by howardhsien** [comment]
My react version is 15.3.1.

**Comment by infeng** [comment]
I don`t know what`s wrong, can you offer a re-producible demo?

**Comment by howardhsien** [comment]
I found the problems. It should the reason that you have changed the css name (cavans-> canvas). Then we have overwritten the same css class. Therefore the css conflicts. 
Sorry for bothering you.
Thanks for help!

**Comment by infeng** [comment]
:sweat_smile:  I found 'cavans' spell error, so i fix it.
