### ISSUE TITLE
键盘事件可以 stopPropagation 吗？

### ISSUE THREAD

**Issue by jinliming2** [infeng/react-viewer#81]
键盘事件 `esc` 被上层 DOM 触发，导致外层的 DOM 被关闭。

键盘事件如果是被 viewer 成功触发的话，应该阻止继续冒泡。

但是现在事件好像是直接绑在 body 上的，这个能调整一下吗？

**Comment by infeng** [comment]
可以给一个重现的demo吗

**Comment by jinliming2** [comment]
https://codesandbox.io/s/laughing-https-34bj9

**Comment by infeng** [comment]
[v2.11.1](https://github.com/infeng/react-viewer/releases/tag/v2.11.1) 修复了这个问题

**Comment by infeng** [comment]
https://codesandbox.io/s/priceless-varahamihira-13ojb
