### ISSUE TITLE
Super expression must either be null or a function

### ISSUE THREAD

**Issue by ke-chenyan** [infeng/react-viewer#84]
我在生产环境页面打开会直接报错Super expression must either be null or a function，但是在本地开发环境是没问题的。其他人是否也遇到了同样问题？
版本：  "react": "^16.8.6",
              "react-dom": "^16.8.6",
              "react-viewer": "^3.0.0"

**Comment by infeng** [comment]
可以贴一下 `webpack` 配置吗

**Comment by ZiQiangWang** [comment]
遇到了相同的问题

**Comment by ke-chenyan** [comment]
> 遇到了相同的问题

可以贴一下 webpack 配置给作者吗？我这边是公司封装起来的，配置很多，看起来特别乱...

**Comment by infeng** [comment]
可以暂时用 2.x 版本，我今天找一下问题

**Comment by ke-chenyan** [comment]
> 可以暂时用 2.x 版本，我今天找一下问题

辛苦了，感谢

**Comment by infeng** [comment]
可以的话，贴一下你们用到 `react-viewer` 那部分代码

**Comment by federicofalavigna** [comment]
HI! I'm having the same issue! Please, let us know if you have any approach (in english if possible, LOL)

**Comment by miho7031** [comment]
#85 I resolved.

**Comment by infeng** [comment]
Fixed in `v3.0.1`

**Comment by federicofalavigna** [comment]
Thank you! I'll try it!
