### ISSUE TITLE
can't close react-viewer in mobile phones

### ISSUE THREAD

**Issue by howardhsien** [infeng/react-viewer#9]
In computer webpage, I can use "esc" key to exit the viewer, However, in mobile phone when I want to close the viewer, I can't find places to close the viewer.
<img width="245" alt="2017-01-23 12 16 57" src="https://cloud.githubusercontent.com/assets/9826674/22191463/e3fe906c-e165-11e6-9063-55a10b3dd18c.png">

Maybe there can be a gesture or a button available for exiting the viewer?

Thanks!!

**Comment by infeng** [comment]
sorry, react-viewer cant`t support mobile now, i will support it in next version.

**Comment by howardhsien** [comment]
OK Thanks!
Looking forward to the next version.

**Comment by infeng** [comment]
@howardhsien , you can try [react-viewer-mobile](https://github.com/infeng/react-viewer-mobile) in mobile.

**Comment by howardhsien** [comment]
@infeng ,Thanks! I have seen it. It has some great features.
However, why don't you combine react-viewer with react-viewer-mobile? I believe that you will get lot more users if you do so.

**Comment by infeng** [comment]
thanks your suggestion, I will try when I free.
