### ISSUE TITLE
onEvent function

### ISSUE THREAD

**Issue by Frezzaldo** [infeng/react-viewer#90]
It would be nice to get events from the viewer.  For example if I would like to load a highres image when zoomlevel change.

**Comment by infeng** [comment]
This is a good suggestion, let me try to do it

**Comment by mayanksainsburys** [comment]
hi @infeng minScale is not working in chrome

<Viewer
            visible={isVisible}
            onClose={() => { setVisible(false); } }
            images={[{src}]}
            noNavbar={true}
            noToolbar={true}
            noImgDetails={true}
            noFooter={true}
            minScale={1}
