### ISSUE TITLE
Changes in 3.2.0 are breaking changes

### ISSUE THREAD

**Issue by beevelop** [infeng/react-viewer#98]
In the new `3.2.0` version the CSS stylesheet has been removed and adding the line 
```js
import 'react-viewer/dist/index.css';
```
is mandatory to use `react-viewer` any further. This is literally a **breaking** change and would require a `4.0.0` release in semver.

I guess a few more users of your library might stumble upon this, so I'd highly recommend to put a big disclaimer in the README about the change or tag the release as 4.0.0.

**Comment by infeng** [comment]
You are right, I will release `3.2.1` to fix this breaking change.

**Comment by beevelop** [comment]
Alright, thank you 🍻
